### ISSUE TITLE
Expose the chart component, instead of packaging as plugin.

### ISSUE THREAD

**Issue by jondavidjohn** [JustSteveKing/vue2-frappe#10]
I'd prefer it if you'd just expose the Chart component directly instead of forcing the use of `Vue.use` and global registration.

I'd love to be able to use it just locally within a given component w/o registering it globally.

```js
import VueFrappe from 'vue2-frappe'

export default {
  components: { VueFrappe },
  ...
}
```

And if someone _wants_ to use it globally, it's pretty easy to register it yourself.

**Comment by JustSteveKing** [comment]
Hi @jondavidjohn that would be quite a breaking change to implement at this time, so perhaps it is something I should document to make a little easier?

Happy to take a vote on this one to be honest!

**Comment by JustSteveKing** [comment]
Closing as too much of a breaking change
