### ISSUE TITLE
Can't update chart

### ISSUE THREAD

**Issue by matiaslopezd** [JustSteveKing/vue2-frappe#14]
How update chart? Thanks!

In API Frappe Chart the function update(Object), allow update data but, is impossible make that.

API: https://frappe.io/charts/docs/reference/api

**Comment by JustSteveKing** [comment]
Hey @matiaslopezd I will have a look into this, unless you want to submit a PR?

Was thinking about building a v2.0 soon

**Comment by JustSteveKing** [comment]
@matiaslopezd I have extended the mixin to include the `update` method - something I hadn't done. I have yet to test it so may not work quite as expected

**Comment by ssuess** [comment]
Hi I know this is a bit old, but any tips for using the update method? I can't seem to get it to work. I have tried `chart.update(data)` and `this.chart.update(data)` to no avail. How should I reference this? Thanks!

**Comment by ssuess** [comment]
ok, figured out how to do this (at least one way): I added a ref for the item in the template, and then updated it by using the ref (`this.$refs.myChart.update(data)`)
