### ISSUE TITLE
BABEL/WEBPACK Failed to compile

### ISSUE THREAD

**Issue by andrehsmendes** [JustSteveKing/vue2-frappe#17]
` ERROR  Failed to compile with 1 errors                                  14:39:08
 error  in ./node_modules/vue2-frappe/src/mixins/index.js

Module parse failed: Unexpected token (230:19)
You may need an appropriate loader to handle this file type.
|
|             const options = (this.type === 'heatmap')
|                 ? {...baseOptions, ...heatMapOptions}
|                 : {...baseOptions, ...chartOptions}
|

 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./node_modules/vue2-frappe/src/components/Charts/Chart.vue 6:0-39 @ ./node_modules/vue2-frappe/src/components/Charts/Chart.vue
 @ ./node_modules/vue2-frappe/src/components/Charts/index.js
 @ ./node_modules/vue2-frappe/src/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js`

----

I'm getting this error with my current setup.

Possible solution would be using **Object.assign(baseOptions, heatMapOptions)**.

**Comment by JustSteveKing** [comment]
Just published now:

```
const options = Object.assign(
    baseOptions,
    (this.type === 'heatmap') ? heatMapOptions : chartOptions
)
```
