### ISSUE TITLE
Destroy chart

### ISSUE THREAD

**Issue by samir-ben** [JustSteveKing/vue2-frappe#18]
I thank you for your work,

I use the vue2-frappe on the SPA website and I need to destroy the chart (after going to another page),
because if I don’t follow this, I will receive a lot of errors:

```
Error: <rect> attribute x: Expected length, "NaN"
Error: <rect> attribute width: Expected length, "NaN".
....
```
In my Vue Component, I used the same example syntax with `<vue-frappe>` template of the documentation.
Can you help me to fix this problem ?

Thank you

**Comment by JustSteveKing** [comment]
Hi @samir-ben is there any chance you could show me some code example of your implementation?

**Comment by JustSteveKing** [comment]
No reply, closing for now
