### ISSUE TITLE
My Pie isn't round?!

### ISSUE THREAD

**Issue by tommed** [JustSteveKing/vue2-frappe#19]
Probably doing something silly, so apologies if this is the case. I have installed frappe to Vue (via CLI 3) like so:

main.js
```javascript
import VueFrappe from 'vue2-frappe'
// ...
Vue.use(VueFrappe)
```

Then, I'm using it like so:

Statistics.vue
```javascript
<vue-frappe id="ratio" 
              type="pie"
              :maxSlices="5"
              :height="600" 
              :labels="[...]" 
              :dataSets="[{name: 'breakdown', values: [...]]" />
```

Where the data is 8 values.

When rendered, I get this:
![Rendered](https://livestore.blob.core.windows.net/public/vue-frappe-issue.png)

...and my console contains zero warnings/errors. Any ideas?

FYI, I'm using Bootstrap Vue within this site and FontAwesome (via remote CSS stylesheet).

**Comment by JustSteveKing** [comment]
Sorry it's taken me awhile to get to this, is there any chance you could show me the implementation?

**Comment by JustSteveKing** [comment]
No response, closing for now
