### ISSUE TITLE
Sometimes, it appears longer, and leaves the page

### ISSUE THREAD

**Issue by pirmax** [JustSteveKing/vue2-frappe#20]
I've an issue with chart...

Sometimes, the graph is displayed normally, in the Bootstrap container. Sometimes, it appears longer, and leaves the page.

My code: https://pastebin.com/raw/3P0JYqYr

Has someone already had this problem ?

Here the delimiter of container div:

![image](https://user-images.githubusercontent.com/1739235/55668447-db44af00-586a-11e9-9076-7ef0fbb9a726.png)

Sometimes, it's ok:

![image](https://user-images.githubusercontent.com/1739235/55668464-029b7c00-586b-11e9-8116-d83a8a28d405.png)

**Comment by JustSteveKing** [comment]
This isn't something I've noticed yet to be honest! If you inspect the element are there any overflow issues?? The data points your using, are they extending the graph past the container?

One thing that springs to mind is that you have given the chart a height which will allow the chart to stretch to whatever width is required. My thoughts on this are if you remove the width does it fit the container? If so, I would add a style rule to force scroll on overflow-x

**Comment by pirmax** [comment]
Always the same problem by removing the height. I look for the rest.

**Comment by JustSteveKing** [comment]
@pirmax I would recommend trying some style rules to force the chart to stay within its container. As this is not an issue with the component itself I will close this issue, but please feel free to comment further if needed.
