### ISSUE TITLE
Cannot use the library as a plugin with nuxt

### ISSUE THREAD

**Issue by IndianTinker** [JustSteveKing/vue2-frappe#21]
Hey, A beginner with Vue/Nuxt here.
I have used frappe [before](http://rohitg.in/2018/05/04/Jalajap/) directly in the HTML page. The library is cool. Thanks for taking the time to make it work with Vue. I am having trouble having to get it work with nuxt. I installed the library and included it as a [plugin in nuxt](https://nuxtjs.org/api/configuration-plugins). But somehow, it never mounts. 

I tried other libraries like [vueBar](https://github.com/DeviaVir/vue-bar) and [vueTrend](https://github.com/QingWei-Li/vue-trend) too. They work based on the nuxt documentation. 
It would be great if you could look into this issue ! 😄 

I used [this](https://alligator.io/vuejs/vue-frappe-charts/) tutorial as the documentation.

**Comment by IndianTinker** [comment]
Super Sorry ! The problem was with the tutorial. I had to use the name as 'chart' which allows using <vue-frappe> component. Damn, I was being so stupid. 😞 

Like you meantion in the readme .
```
import Chart from 'vue2-frappe'
Vue.use(Chart)
```

**Comment by MyIsaak** [comment]
I am having the same issue and wrote exactly what you did. Can you please test it again?

I get the error `Cannot use import statement outside a module`

**Comment by IndianTinker** [comment]
Hey, did you add it as a plugin in nuxtjs's config file, like this ?

```
  plugins: [{
    src: '~/plugins/vue-frappe.js',
    ssr: false
  }],
```

**Comment by MyIsaak** [comment]
No. But perhaps the reason I had this error was due to the fact I used SSR.
Why should I disable it? Wouldn't it be a good idea performace wise to
render it on the server side?
