### ISSUE TITLE
Automatically update Chart

### ISSUE THREAD

**Issue by ajusa** [JustSteveKing/vue2-frappe#22]
Hello,
Thank you for putting together this library! I was wondering if it would be possible for you to have the chart update once the source data changes. For example, you could put a watcher on "this.data" and then have it call the "update" method that is already a part of the component. 

Doing this would make it reactive, and it would improve performance. Right now, the only way to have the chart update is to use refs, as specified in #14, or to key the chart with the data source, so that it is destroyed and re-rendered every time the source data changes.
Thanks!

**Comment by JustSteveKing** [comment]
Hey @ajusa thanks for using the library! I have been thinking about how I can improve this library recently - I will see what I can do!

**Comment by JustSteveKing** [comment]
Hey @ajusa thanks for using the library! I have been thinking about how I can improve this library recently - I will see what I can do!

**Comment by NicJG** [comment]
Giving this a go for hacktoberfest ✌🏻
