### ISSUE TITLE
on load, chart width taking whole page width

### ISSUE THREAD

**Issue by danielcharrua** [JustSteveKing/vue2-frappe#28]
Hello, I have a <vue-frappe> component inside a Bootstrap 4 card, nothing fancy...
On page load, the chart renders with the whole page width and sometimes with the correct card size. 

The div that is not sizing as it should is <svg class="frappe-chart chart" width="1384" height="300">

Height is all right but not width. I have created a video to see the issue. You'll se me updating the page to see this width issue. 
https://youtu.be/snZxzWSmePI

If you resize the window, chart width gets corrected.

```
<vue-frappe
  id="production"
  :labels="this.data.labels"
  title=""
  type="axis-mixed"
  :height="300"
  :colors="['#609700', 'red']"
  :lineOptions= {regionFill:1}
  :dataSets="this.values">
</vue-frappe>
```

<img width="1608" alt="Captura de pantalla 2019-09-27 a las 13 29 29" src="https://user-images.githubusercontent.com/31829061/65766339-f82bb200-e12a-11e9-8759-562d272a7a61.png">
<img width="1612" alt="Captura de pantalla 2019-09-27 a las 13 29 47" src="https://user-images.githubusercontent.com/31829061/65766340-f82bb200-e12a-11e9-849b-8350f81c7ee1.png">

Any ideas?
Thank you.

**Comment by JustSteveKing** [comment]
Hey @danielcharrua thanks for using the package!

I will probably have a look into this over the weekend/early next week

**Comment by danielcharrua** [comment]
Great, thank you @JustSteveKing!

**Comment by JustSteveKing** [comment]
@danielcharrua however if you are taking part in Hacktoberfest I was planning on adding the tag!

**Comment by danielcharrua** [comment]
I wasn't aware of Hacktoberfest, but yes! no problem at all :)

**Comment by danielcharrua** [comment]
This issue has nothing to do with your integration, apparently was a CSS issue.
