### ISSUE TITLE
dataSets: TypeError: a is null

### ISSUE THREAD

**Issue by fansanelli** [JustSteveKing/vue2-frappe#35]
Hello,
I'm trying to build a reactive page with both dataset and labels computed using Axios to perform the server call and pushing results into an array called "statistiche".
Then I did something like this:
```
<template>
    <vue-frappe
      id="grafico"
      :labels="this.legenda"
      type="pie"
      :height="400"
      :dataSets="this.valori">
    </vue-frappe>
</template>
```
and below:
```
  computed: {
    valori () {
      return [{ 'values': this.statistiche.map(stat => stat.valore) }]
    },
    legenda () {
      return this.statistiche.map(stat => stat.chiave || '(nessuna)')
    }
```
when I change when the array changes I get:

```
[Vue warn]: Error in callback for watcher "dataSets": "TypeError: a is null"

found in

---> <VueFrappe> at node_modules/vue2-frappe/src/components/Charts/Chart.vue
       <QPage>
         <Statistiche> at src/pages/Statistiche.vue
           <QPageContainer>
             <QLayout>
               <MyLayout> at src/layouts/MyLayout.vue
                 <App> at src/App.vue
                   <Root> vue.runtime.esm.js:619
    VueJS 8
TypeError: "a is null"
    animateSVG frappe-charts.min.esm.js:1
    animateSVG frappe-charts.min.esm.js:1
    runSMILAnimation frappe-charts.min.esm.js:1
    value frappe-charts.min.esm.js:1
    value frappe-charts.min.esm.js:1
    update Chart.vue:263
    dataSets Chart.vue:192
    VueJS 4
vue.runtime.esm.js:1888
    VueJS 7
```
​and the "legend" never shows.. Can you please check?
Many thanks
Francesco
P.S. without this:

```
<style>
.frappe-chart {
  overflow: visible !important;
}
</style>
```

I see the legend cutted anyway

**Comment by fansanelli** [comment]
I commented this code:

```
        watch: {
           // labels() {
           //     this.update()
           // },
```

and the error disappeared... But the labels are not shown (until a redraw is forced)...

**Comment by leobarcellos** [comment]
You have a typo in your template syntax, you can't use "this" there. 
Fixed code:

```
<vue-frappe
      id="grafico"
      :labels="legenda"
      type="pie"
      :height="400"
      :dataSets="valori">
    </vue-frappe>
```

**Comment by fansanelli** [comment]
I'm not sure this could fix the issue... I found another library that accept both dataset and label in a single object. In that way it worked.

**Comment by JustSteveKing** [comment]
This is mapping props directly to frappe options at time of building, so it was aimed to reflect frappe. If alternative props are required I'm happy to open this up to a discussion. I am currently planning a V2 which will have breaking changes I assume
