### ISSUE TITLE
Expose the VueFrappe component to allow direct import as the README suggests

### ISSUE THREAD

**Issue by AtriLahiji** [JustSteveKing/vue2-frappe#36]
I've been using vue2-frappe for a wip project and noticed that despite what the README may say, it is not currently possible to import the Chart component as VueFrappe. I fixed it locally, but would like to see this fixed in a new release. The new src/index.js would be as follows:

```
import { Chart } from './components/Charts'

export {
  Chart as VueFrappe
}

export default {
    install (Vue, options) {
        Vue.component('vue-frappe', Chart)
    }
}
```

**Comment by AtriLahiji** [comment]
Thanks for the merge friend! I'll use the NUXT plugin I made until there are enough commits to warrant tagging a new release.

**Comment by budkin76** [comment]
> Thanks for the merge friend! I'll use the NUXT plugin I made until there are enough commits to warrant tagging a new release.

Hi @AtriLahiji I just opened an issue requesting this release https://github.com/JustSteveKing/vue2-frappe/issues/46
