### ISSUE TITLE
JS Errors on resizing browser window

### ISSUE THREAD

**Issue by rogiervanderheijden** [JustSteveKing/vue2-frappe#38]
Hi,

I use Vue 2 Frappe chart type `axis-mixed` for my project and get a load of errors on resizing my browser window. Have looked into online solutions, but none have helpt me yet.

I have attached an image with some of the errors.
![image](https://user-images.githubusercontent.com/26439378/71326663-3e13ce80-24fe-11ea-859b-a0de731ff03c.png)

If you need some other info on my project please let me know.

Hope someone can help me out.

**Comment by rogiervanderheijden** [comment]
The answer here talks about a solution:
https://github.com/frappe/charts/issues/212

But the frappe charts version I see in my yarn.lock (as dependency from vue2-frappe) is 
```frappe-charts@^1.3.0:
  version "1.3.0"

**Comment by JustSteveKing** [comment]
More than happy to accept a PR on this

**Comment by rogiervanderheijden** [comment]
Hi Steve,

If I can create a fix, I will create a PR on it.

Cheers,
Rogier
