### ISSUE TITLE
'VueFrappe' was not found

### ISSUE THREAD

**Issue by goaround** [JustSteveKing/vue2-frappe#40]
I tried to use the component directly but it seems that the npm version does not contain this possibility. The documentation is different from here on Github: https://www.npmjs.com/package/vue2-frappe

**Comment by JustSteveKing** [comment]
The component was not designed to be used directly, it was designed as a wrapper component only.

**Comment by budkin76** [comment]
@goaround Having the same issue and thus opened this issue: https://github.com/JustSteveKing/vue2-frappe/issues/46
