### ISSUE TITLE
HeatMap and Vue.js

### ISSUE THREAD

**Issue by ChungMasterFlex** [JustSteveKing/vue2-frappe#42]
Has anybody had any luck using the heatmap?  I must be misunderstanding how to use it - would love a pointer to a repo of a working example (with a couple dates + data) - thank you so much.  If it's helpful, I'm very happy to copy/paste my vue component.

**Comment by JustSteveKing** [comment]
If you share an example of what you are doing, I would be more than happy to have a look!

I'm currently planning a new release to fix issues like this, and to prepare for VueJS3

**Comment by ChungMasterFlex** [comment]
Thank you!  @JustSteveKing 

```
<template>
  <div id="activeTest">
    Heat Map
    <vue-frappe
        id="test2"
        :labels="[
            '12am-3am', '3am-6am', '6am-9am', '9am-12pm',
            '12pm-3pm', '3pm-6pm', '6pm-9pm', '9pm-12am'
        ]"        
        title="My Heatmap Chart"
        type="heatmap"
        :height="300"
        :colors="['#ebedf0', '#c0ddf9', '#73b3f3', '#3886e1', '#17459e']"
        :dataSets="this.data">
    </vue-frappe>      
  </div>
</template>
<script>

export default {
  name: 'ActiveTest',
    data () {
                return {
                    dataPoints: {
                        '1524064033': 8
                    }, countLabel: 'Level',

                    startDate: new Date('2019-02-16T00:00:00'),                    
                    endDate: new Date('2020-02-15T00:00:00')                    
                }
            }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
#graphsGraphsGraphs {
  align-items: center;
  border: 1px dashed darksalmon;
  width: 75vh;
}

.beforeLine::after {

  border-bottom: 12px solid blue;

  border-bottom: 12px solid #2c3e50;
  width: 100%;
  content: "";
  position: absolute;
  padding: 15px;
  left: 0px;
}

.twoColumnEvenFlex {
  display: flex;
  justify-content: space-evenly;
  align-items: center;
  text-align: right;
  
}

.threeRowsEvenFlex {
  display: flex;
  flex-direction: column;
  justify-content: space-evenly;
  align-items: center;
}

.sixStack {
  height: 30vh;
  color: #2c3e50;
}

#activeTest {
}

</style>
```

**Comment by ChungMasterFlex** [comment]
![image](https://user-images.githubusercontent.com/200106/79360486-fcc28700-7f11-11ea-98d4-7e312b8a9183.png)

**Comment by JustSteveKing** [comment]
Thanks @ChungMasterFlex !

I will have a look into this and have a play, I didn't get chance to test/try all variations of all the charts so I am assuming this is one that may not be working 100%.

Also, I really need to work on some docs ....

**Comment by ChungMasterFlex** [comment]
Hey @JustSteveKing any luck?

**Comment by JustSteveKing** [comment]
Hey @ChungMasterFlex I have updated to the latest frappe library underneath now, please update to 1.2.0 and let me know if you are having issues at all - I can then reinvestigate

**Comment by jonalxh** [comment]
Any update? I've tried with your example and does not work in latest version.
