### ISSUE TITLE
`tooltipOptions` shouldn't have defined options by default

### ISSUE THREAD

**Issue by hmaesta** [JustSteveKing/vue2-frappe#45]
By default, `vue2-frappe` is applying options to `tooltipOptions`:

https://github.com/JustSteveKing/vue2-frappe/blob/d8bbf7670e5792693dc8bdb8e5fc742ea09cf80e/src/components/Charts/Chart.vue#L159-L168

This is not the default behavior of `frappe-charts`: [(_source_)](https://github.com/frappe/charts/blob/f06d0c70afe65d80cb118df961623934fbc4674e/src/js/charts/AxisChart.js#L36)

```js
options.tooltipOptions = options.tooltipOptions || {};
```

I suppose that this code comes from a [documentation example](https://frappe.io/charts/docs/basic/annotations#tooltips).

**Comment by JustSteveKing** [comment]
Yes this comes out from the docs, and it was perfect for what I needed from it. However, if this is causing a problem I will address it in the next release.
