### ISSUE TITLE
A new release is needed to reflect changes made to the import after the last one

### ISSUE THREAD

**Issue by budkin76** [JustSteveKing/vue2-frappe#46]
Hello,

I was having trouble getting the component to work directly as stated in the Readme and discovered that @AtriLahiji made an addition to the import and also updated the Readme (https://github.com/JustSteveKing/vue2-frappe/pull/37). Could we get a new release tagged to reflect these changes? Thanks!

**Comment by AtriLahiji** [comment]
My changes to the readme were trivial and I didn't really change it functionally. My PR was aimed at ensuring one could actually follow the readme. Unless you're super fixed on using frappe charts specifically, I moved to using Apex Charts for my project: https://git.atrilahiji.dev/atrilahiji/pollo/src/branch/master/plugins

**Comment by budkin76** [comment]
FYI the workaround for this (to use the component directly) is to import like this:

`import { Chart as VueFrappe } from 'vue2-frappe/src/components/Charts';`

**Comment by JustSteveKing** [comment]
I have published a new release to update to the latest Frappe library, could you please confirm if this is an issue after updating?
