### ISSUE TITLE
Example doesn't seem to work

### ISSUE THREAD

**Issue by Rednas83** [JustSteveKing/vue2-frappe#59]
Tried the wrapper, but the provided example doesn't seems to work.
https://codepen.io/rednas83/pen/abZMopb

Also tried the global approach but then it returns a warning
![image](https://user-images.githubusercontent.com/25219229/99192765-05fc2680-2775-11eb-87a2-65ab91b77cb8.png)

Any help is greatly apreciated

**Comment by codepotato** [comment]
Codepen link doesn't work
