### ISSUE TITLE
areaFill is not set to "1"

### ISSUE THREAD

**Issue by maximus1010101** [JustSteveKing/vue2-frappe#6]
Hello,
I use :lineOptions="{areaFill: 1, hideDots: 1}".
"hideDots" is work, but "areaFill" is not. I try remove "hideDots", "areaFill" is not set too.

**Comment by JustSteveKing** [comment]
Hi @maximus1010101 any chance you could share a repo or how you are implementing this?

**Comment by maximus1010101** [comment]
Excuse me for troubling.

I should have used a "regionFill", as in the default prop "lineOptions" of your component.
I was deceived by the instruction the "frappe":
https://frappe.io/charts/docs/basic/trends_regions

OFFTOP:
Maybe I do not understand something... Why the prop "id" is required? You can use in "startChart" function something like this:

this.chart = new Chart(this.$el, {
        data: this.data,
        title: this.title,
        ...
});

**Comment by JustSteveKing** [comment]
Hi @maximus1010101 Using `this.$el` is to bind to the first element in a slot is it not? The purpose of this library is to create it using the component itself not bind to a slot.

I created this library on a Friday afternoon as a test as it is something I am going to need in the near future.

About to push a fix up now

**Comment by JustSteveKing** [comment]
Pushed changes and published to npm

**Comment by maximus1010101** [comment]
`this.$el` is the root DOM element that the Vue instance is managing. I tried my example works correctly.)

**Comment by maximus1010101** [comment]
Thanks you!
