### ISSUE TITLE
Initial data load: lines not rendering

### ISSUE THREAD

**Issue by eminkel** [JustSteveKing/vue2-frappe#7]
Thanks for your hard work on this awesome vue mixin for Frappe.

I'm running into an issue where after initial render the lines do not render with the chart. The tooltip hovers work and have the correct data. This may be a familiar issue I ran into with other charting solutions, just can't remember what I did previously to get around it.

Any ideas?

Here's an animation of the issue: **https://i.imgur.com/le4SzaR.gif**

Edit:
I was able to render the chart by holding up the component to load after data was completely loaded. Seemed to work. You can close this. If you have any other ideas for work arounds, I'd love to hear them.

**Comment by sifex** [comment]
Agreed, this isn't the best solution. PR is required to update the chart data whenever `:dataSets` or `:labels` is updated
